apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fast-helm.selectorLabels" . | nindent 4 }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: http
      port: {{ .Values.image.servicePort }}
      targetPort: {{ .Values.image.containerPort }}
  selector:
    {{- include "fast-helm.selectorLabels" . | nindent 4 }}
