name: Run unit tests CI

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: [main]


jobs:
  run_tests:
    name: Run unit-tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.4

      - name: Upgrade pip
        run:
          python -m pip install --upgrade pip

      - name: Install poetry and all project dependencies
        run: |
          pip install poetry
          poetry install 

#      - name: Launch pytest
#        run: |
#          poetry run pytest

#      - name: Launch mypy
#        run: |
#          poetry run mypy .

#      - name: Launch pylint
#        run: |
#          poetry run pylint ./app
